export enum ErrorCode {
    PASSWORD_DOES_NOT_MATCH = 'PASSWORD_DOES_NOT_MATCH',
    CLIENT_ROLE_MISSING = 'CLIENT_ROLE_MISSING',
    EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
    USER_OR_PASSWORD = 'USER_OR_PASSWORD',
}